/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.io.IOException;
import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, IOException {
        TestCases tests = new TestCases(); // Initialize your test class

        // TODO: call your test case functions one after other here

        // tests.testCase01();
        // tests.testCase02();
        // tests.testCase03();
        // tests.testCase04();
        // tests.TestCases05();
        tests.TestCases06();
        // tests.TestCases07();
        // tests.TestCases08();
        // tests.TestCases09();
        // tests.TestCases10();

        // END Tests

        tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
